datalore-env-format-version: "0.2"
datalore-package-manager: "pip"
datalore-base-env: "default"
dependencies:
- pip:
  - folium
  - plotly-express
  - goo
  - airtable
  - mlx.warnings
  - warnings-plugin
  - jupyter-dash
